### ISSUE TITLE
Dernière version

### ISSUE THREAD

**Issue by Zokiasu** [ajpproject/Rogopoly#3]
[Rogopoly.zip]

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1821979/Rogopoly.zip)

**Comment by jilink** [comment]
Version final de map (normalement)
il suffit de faire une new map pour qu'elle se crée et s'affiche toute seule, pas besoin d'appeler de fonction
[map.zip](https://github.com/ajpproject/Rogopoly/files/1823073/map.zip)

**Comment by Hawkx78** [comment]
map et move pour jimjim
[map.zip](https://github.com/ajpproject/Rogopoly/files/1825225/map.zip)

[move.zip](https://github.com/ajpproject/Rogopoly/files/1825223/move.zip)

**Comment by Zokiasu** [comment]
Equipment et character 
[character.zip](https://github.com/ajpproject/Rogopoly/files/1825246/character.zip)
[equipment.zip](https://github.com/ajpproject/Rogopoly/files/1825247/equipment.zip)

**Comment by jilink** [comment]
première version d'item et de ma page de test

[item.zip](https://github.com/ajpproject/Rogopoly/files/1826256/item.zip)


[test.zip](https://github.com/ajpproject/Rogopoly/files/1826258/test.zip)

**Comment by jilink** [comment]
l'inventaire d'item et une fonction pour le tester, (si vous voulez le tester il vous suffit d'écrire : new testJimmy("stock"); (dans le main))

[test.zip](https://github.com/ajpproject/Rogopoly/files/1830411/test.zip)
[inventaire.zip](https://github.com/ajpproject/Rogopoly/files/1830412/inventaire.zip)

**Comment by Zokiasu** [comment]
J'ai ajouté tout ce qui a été envoyé précédemment dans le fichier j'ai fait des petits modif sur les fichiers où Jimmy utilise mes fonctions parce que j'ai changer les nom et j'ai changer le nom du fichier d'Alex du coup j'envoie le tout avec les dépendances de faite !

[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1831059/Rogopoly.zip)

**Comment by Zokiasu** [comment]
Ajout de l'inventaire d'armure et modif de pas mal de package... :x
Modification de package : 
[character.zip](https://github.com/ajpproject/Rogopoly/files/1831603/character.zip)
[equipment.zip](https://github.com/ajpproject/Rogopoly/files/1831604/equipment.zip)
[inventory.zip](https://github.com/ajpproject/Rogopoly/files/1831605/inventory.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1831606/test.zip)

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1832287/Rogopoly.zip)

**Comment by jilink** [comment]
inventaire d'item finit, ces packages modifiés (n'oubliez pas de remplacer seulement testJimmy.java dans la package test et pas tout le package pour ne pas supprimer les autre) 

pour tester l'inventaire d'item :     	new testJimmy("stock");

[inventory.zip](https://github.com/ajpproject/Rogopoly/files/1834721/inventory.zip)
[item.zip](https://github.com/ajpproject/Rogopoly/files/1834722/item.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1834723/test.zip)

**Comment by Zokiasu** [comment]
Début système fight et d'autre modif que j'ai oublié + tout ce qui a été mis avant :D 
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1843422/Rogopoly.zip)

**Comment by Hawkx78** [comment]
[gestion.zip](https://github.com/ajpproject/Rogopoly/files/1844292/gestion.zip)
[move.zip](https://github.com/ajpproject/Rogopoly/files/1844293/move.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1844294/test.zip)
voila

**Comment by jilink** [comment]
modification de stock et testJimmy ;))))
[test.zip](https://github.com/ajpproject/Rogopoly/files/1844374/test.zip)
[inventory.zip](https://github.com/ajpproject/Rogopoly/files/1844375/inventory.zip)

**Comment by Zokiasu** [comment]
(J'écris d'avance pour pas oublié)
Player, fightsystem, test

**Comment by jilink** [comment]
chargement d'une map aléatoire à la fin de chaque niveau, testez avec new testJimmy("lvl");
  
[gestion.zip](https://github.com/ajpproject/Rogopoly/files/1848632/gestion.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1848633/test.zip)

**Comment by Zokiasu** [comment]
[character.zip](https://github.com/ajpproject/Rogopoly/files/1848768/character.zip)

**Comment by jilink** [comment]
liste de mob avec leur positions ( la liste se crée automatiquement au lancement d'une map)

[map.zip](https://github.com/ajpproject/Rogopoly/files/1850929/map.zip)

**Comment by Zokiasu** [comment]
[character.zip](https://github.com/ajpproject/Rogopoly/files/1852805/character.zip)

**Comment by jilink** [comment]
interface générale, testez en écrivant new testJimmy("gen"); (et petite modification de map)
[affichage.zip](https://github.com/ajpproject/Rogopoly/files/1852910/affichage.zip)
[map.zip](https://github.com/ajpproject/Rogopoly/files/1852911/map.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1852913/test.zip)

**Comment by jilink** [comment]
Vous pouvez jouer avec la nouvelle interface : new testJimmy("lvl");
et tester l'interface de création new testJimmy("crea");

[affichage.zip](https://github.com/ajpproject/Rogopoly/files/1856963/affichage.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1856964/test.zip)

**Comment by Zokiasu** [comment]
Version X de mes trucs que j'ai oublié :D

**Comment by Hawkx78** [comment]
[move.zip](https://github.com/ajpproject/Rogopoly/files/1859127/move.zip)
[save.zip](https://github.com/ajpproject/Rogopoly/files/1859128/save.zip)
[gestion.zip](https://github.com/ajpproject/Rogopoly/files/1859129/gestion.zip)
JE VEUX LA VERSION COMPLETE PLS

**Comment by Zokiasu** [comment]
Voilà
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1859135/Rogopoly.zip)

**Comment by Zokiasu** [comment]
[character.zip](https://github.com/ajpproject/Rogopoly/files/1859352/character.zip)

**Comment by Zokiasu** [comment]
[character.zip](https://github.com/ajpproject/Rogopoly/files/1859498/character.zip)

**Comment by Zokiasu** [comment]
[character.zip](https://github.com/ajpproject/Rogopoly/files/1859513/character.zip)

**Comment by Zokiasu** [comment]
J'ai jouté les trucs de jimmy, mes trucs et les derniers truc qu'Alex à envoyé mais vu que t'as fait des modifs alex faudra nous les envoyé :o 
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1859744/Rogopoly.zip)

**Comment by Zokiasu** [comment]
Quand vous faite le dl récupéré pas les fichiers que vous êtes en train de modifié soyez logique :D

**Comment by Zokiasu** [comment]
Modification de la classe character et package en entity du coup toute vos initialisation en caractère faudra les modifiés en entité pour évité la confusion avec la classe character de java.

[entity.zip](https://github.com/ajpproject/Rogopoly/files/1860333/entity.zip)

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1860352/Rogopoly.zip)

**Comment by jilink** [comment]
on peut se faire agro par des mobs, faites juste new testJimmy("Game");
et assistez à la magie ;))

[test.zip](https://github.com/ajpproject/Rogopoly/files/1860783/test.zip)
[UI.zip](https://github.com/ajpproject/Rogopoly/files/1860784/UI.zip)

**Comment by Hawkx78** [comment]
[move.zip](https://github.com/ajpproject/Rogopoly/files/1860961/move.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1860962/test.zip)

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1860968/Rogopoly.zip)
Y a tout dedans

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1861030/Rogopoly.zip)

**Comment by Zokiasu** [comment]
Modification de testAlexandre, testJimmy, test, move (Désolé mais j'avais besoin d'un mouv fonctionnel pour des test du coup j'ai finis corrigé ce que t'as fait alex y avait rien à modifié hormis ajouter l'entité player)

[move.zip](https://github.com/ajpproject/Rogopoly/files/1861298/move.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1861299/test.zip)
[entity.zip](https://github.com/ajpproject/Rogopoly/files/1861306/entity.zip)
[fightsystem.zip](https://github.com/ajpproject/Rogopoly/files/1861307/fightsystem.zip)

**Comment by Zokiasu** [comment]
J'ai modifié testGame dans testJimmy pour ajouter le skill de fuite avec la fonction qui agis sur le déplacement :D C'est tout à la fin ma modif sur le testjimmy
[fightsystem.zip](https://github.com/ajpproject/Rogopoly/files/1863630/fightsystem.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1863631/test.zip)

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1864299/Rogopoly.zip)

**Comment by Zokiasu** [comment]
Ajout des effets des skills existant.
Ajout du remplacement des monstres mort par des coffres.
Ajout de l'affichage des dégâts et des skills utilisé pendant les combats.
Ajout du pnj intendant dans la classe npc

[entity.zip](https://github.com/ajpproject/Rogopoly/files/1865500/entity.zip)
[fightsystem.zip](https://github.com/ajpproject/Rogopoly/files/1865501/fightsystem.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1865502/test.zip)

**Comment by Zokiasu** [comment]
[entity.zip](https://github.com/ajpproject/Rogopoly/files/1865551/entity.zip)
[fightsystem.zip](https://github.com/ajpproject/Rogopoly/files/1865552/fightsystem.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1865553/test.zip)

**Comment by jilink** [comment]
interface pnj, lancez new testJimmy("game") et passez à coté d'un pnj

[map.zip](https://github.com/ajpproject/Rogopoly/files/1865764/map.zip)
[test.zip](https://github.com/ajpproject/Rogopoly/files/1865765/test.zip)
[UI.zip](https://github.com/ajpproject/Rogopoly/files/1865766/UI.zip)

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1866201/Rogopoly.zip)

**Comment by Zokiasu** [comment]
Pour pallier au petit problème du dernier fichier
[fightsystem.zip](https://github.com/ajpproject/Rogopoly/files/1866217/fightsystem.zip)

**Comment by Zokiasu** [comment]
[entity.zip](https://github.com/ajpproject/Rogopoly/files/1866238/entity.zip)

**Comment by Zokiasu** [comment]
[fightsystem.zip](https://github.com/ajpproject/Rogopoly/files/1866570/fightsystem.zip)
[map.zip](https://github.com/ajpproject/Rogopoly/files/1866571/map.zip)
[entity.zip](https://github.com/ajpproject/Rogopoly/files/1866572/entity.zip)

**Comment by jilink** [comment]
tous les pnj sont différenciés (y compris en prison)

[testJimmy.java.zip](https://github.com/ajpproject/Rogopoly/files/1866611/testJimmy.java.zip)
[map.zip](https://github.com/ajpproject/Rogopoly/files/1866612/map.zip)
[UI.zip](https://github.com/ajpproject/Rogopoly/files/1866613/UI.zip)

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1866785/Rogopoly.zip)

**Comment by Zokiasu** [comment]
[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1868667/Rogopoly.zip)

Correction de Creation
Correction de General
Correction IFight
Correction INpc
Correction move
Correction des divers test

**Comment by Zokiasu** [comment]
[testJimmy.zip](https://github.com/ajpproject/Rogopoly/files/1870608/testJimmy.zip)

**Comment by Zokiasu** [comment]
[map.zip](https://github.com/ajpproject/Rogopoly/files/1870683/map.zip)

**Comment by jilink** [comment]
remplace tous ces truc et fait testJimmy("IStock");


[item.zip](https://github.com/ajpproject/Rogopoly/files/1872158/item.zip)
[inventory.zip](https://github.com/ajpproject/Rogopoly/files/1872160/inventory.zip)

[ui.zip](https://github.com/ajpproject/Rogopoly/files/1872150/ui.zip)
[testJimmy.java.zip](https://github.com/ajpproject/Rogopoly/files/1872152/testJimmy.java.zip)

**Comment by Zokiasu** [comment]
J'ai ajouté ce que j'avais fait et ce que t'as fait, je te donne l'honneur de modifié ton interface xD 
L'item j'ai fait quelque modif regarde si ça te convient x) Sinon on reprend l'ancien x)

[Rogopoly.zip](https://github.com/ajpproject/Rogopoly/files/1872392/Rogopoly.zip)
